### ISSUE TITLE
System.ini is not showing the correct stats

### ISSUE THREAD

**Issue by sselvanathan** [mpurses/Sonder#1]
![wrongStats](https://user-images.githubusercontent.com/46525254/90115963-1c997880-dd55-11ea-8b9b-a7fa65a9c991.PNG)

As you can see at the bottom right of the desktop, the CPU and GPU display are completely wrong. Only the memory display is correct.

**Comment by mpurses** [comment]
Thanks for leaving the report. I can confirm on the CPU data being wrong. Never really could get it to match. But that goes with all third party plugins for me (whether it be another Rainmeter skin; even though they should all be doing it the same way; or a monitor like HWINFO). If you find a rainmeter skin or utility that reads what matches in the Task Manager let me know. Task manager may be doing some different math for getting the total? 
I use the builtin plugin for reading the CPU: https://docs.rainmeter.net/manual/measures/cpu/
So maybe try asking the developers on the forums why it doesn't match?

For GPU, mine does display the correct info on my end, but again I'm getting it via Rainmeters plugins, so who knows why there is a discrepancy between different setups. 

Let me know if you find a third party program or Rainmeter skin that does match the Task Manager.
