### ISSUE TITLE
ISS is in the wrong place

### ISSUE THREAD

**Issue by robbely** [mpurses/Sonder#14]
Using the ISS (Space/WorldMap) part of the skin, the ISS appears to be showing approx 100-150 miles ahead of where it should be (compared against live iss feed, esa and heaveansabove locations).

This is possibly due to open-notify.org giving the wrong position data?

**Comment by mpurses** [comment]
Thanks for letting me know, I'll investigate this further to see if I need to switch APIs.

**Comment by robbely** [comment]
As of Apr 10 it seems to be in the right place. I'm not sure if you contacted open-notify but either way lets hope it is a permanent fix :)

**Comment by robbely** [comment]
Closing this as it seems to have resolved itself and hasn't been off since Apr 11 :)
