### ISSUE TITLE
Data for rocket launches gives bad times in Eastern Hemisphere (positive UTC time zones)

### ISSUE THREAD

**Issue by shaktishekhar** [mpurses/Sonder#15]
Data for next 5 rocket launch seems to giving error regex needs to update with latest json response "https://fdo.rocketlaunch.live/json/launches/next/5" as its showing error Webparser Overloaded restart rain meter also it seems that there is time issue as its not picking up any launch time also count down seems not working 
![image](https://user-images.githubusercontent.com/4972171/115645828-aa931d80-a33e-11eb-8b15-5644cc4a1146.png)

**Comment by mpurses** [comment]
Sorry for the late reply.

Usually I show the "Restart Rainmeter" error based on getting a bad time (that's not null) for the next upcoming launch. Which I usually get when Rainmeter's webparser is overloaded and no data is downloaded. It can happen often since the World Map has a lot of webparsing things. I've put in various delays to try to minimize this from happening. 

Anyways... It is weird that is shows up even though there is a date for the next launch. 

I've made a bunch of changes in the mean time to correct errors/issues with getting Rocket Launch data. Could you download this updated version to see if this fixes any issues you have? (I had to put the rmskin file inside a zip file for github)

[Sonder_21.X.0_Test.zip](https://github.com/mpurses/Sonder/files/6510367/Sonder_21.X.0_Test.zip)

> - World Map: Night Shadow Color option
> - World Map: Fix Rocket Launches not updating automatically and add estimated dates instead of TBD if available.
> - Date: StringStyle Setting, Seperate Font Setting from Time skin.
> - Weather: Remove unnessesary refresh at sunrise/set, auto-location bug fixes, slightly faster animations.
> - Add Taiwanese language; Fix German, Slovak, Portuguese.
> - Update default layout to have more consistent theme with 'small' system variations.
> - Other bug fixes and log error cleanup.

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/118854684-979a4b80-b8f2-11eb-96d4-8995eff536b3.png)

![image_15](https://user-images.githubusercontent.com/4972171/118854697-9bc66900-b8f2-11eb-9406-a3387ca8f828.png)


both the information is still wrong kindly have a look

**Comment by mpurses** [comment]
Could you take some screenshots of the measures in the Rainmeter Log > Skins Tab > under "Sonder/Space". As well as make sure there are no errors showing up in the log as well. I feel like something is happening when trying to convert/subtract your time zone or system time possibly.
![Capture](https://user-images.githubusercontent.com/642218/118857576-d0f49c00-b89d-11eb-9268-da0a50d04f1d.PNG)

**Comment by shaktishekhar** [comment]
[https://drive.google.com/file/d/11re-MqjREEzTJJeI0BG21KDLv8bt2qj7/view](url)

check this video

**Comment by mpurses** [comment]
Alright, I think I found the problem, Windows doesn't like the Eastern Hemisphere for whatever reason.. Changed from reading the registry to comparing the Local/UTC Times:
![Screenshot 2021-05-19 135643](https://user-images.githubusercontent.com/642218/118869260-c4c30b80-b8aa-11eb-8f3b-0df415261378.png)


Could you download/replace this file:
https://raw.githubusercontent.com/mpurses/Sonder/master/Skins/Sonder/Space/WorldMapMeasures.inc

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/118904941-76f4e480-b938-11eb-9299-8fbf4099b4c3.png)
i think readings are fine now
![image](https://user-images.githubusercontent.com/4972171/118904966-82e0a680-b938-11eb-9c1a-48cc7b67565c.png)
iss also

but I have a question when I place widget to taskbar the context menu doesn't detect taskbar edge and content goes behind taskbar unlike windows content menu it detects edge and inverts the menu when there is no space at the bottom kindly check screenshot 
![image](https://user-images.githubusercontent.com/4972171/118905124-c4715180-b938-11eb-8471-3fdf6e5458ba.png)
like this looks fine it goes on top 
![image](https://user-images.githubusercontent.com/4972171/118905191-df43c600-b938-11eb-8afa-e437508b0eae.png)
issue is here rocket launches list goes behind taskbar can it be fixed

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/118905263-000c1b80-b939-11eb-96cd-1dfec0dad86a.png)

**Comment by mpurses** [comment]
Thanks for testing that out. 

I don't use the windows context menu for the Rocket Launches, so it's in a fixed location. I'll try to add an option to move it's location up (or something) in the next version. In the mean time you can shift it up a little by changing the Y under [RocketLaunchBackground] in the skin ini file to something like this:
![Screenshot 2021-05-20 081915](https://user-images.githubusercontent.com/642218/118987501-ed4c1380-b945-11eb-9ccb-85e11d3099aa.png)

Also try out TaskbarX if you want a transparent taskbar: https://chrisandriessen.nl/taskbarx

One last question for you, are there any translation errors in the skin/settings when using the Hindi language in the settings (assuming you speak it..)?  It's kind of halfway translated right now.
![Untitled](https://user-images.githubusercontent.com/642218/118989266-82034100-b947-11eb-8f71-e1cd8ade1333.png)

**Comment by shaktishekhar** [comment]
"[RocketLaunchBackground] " is helpful I'll adjust it accordingly and about translation in Hindi it seems all good no spelling error am not so good in Hindi as I speak Hindi but in theory am not so good but I asked my mom she said its all good I think u used google translation one suggestion some words in India is adapted in Hinglish for example now days no one even knows what is
![image](https://user-images.githubusercontent.com/4972171/119010517-c297a480-b9b1-11eb-9949-18ffa55580b4.png)
even villagers knows calender so you better use like this 
![image](https://user-images.githubusercontent.com/4972171/119010779-08546d00-b9b2-11eb-9ba9-30c94eeead72.png)
https://indiatyping.com/index.php/translations/english-to-hindi-translation

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/119013824-fd4f0c00-b9b4-11eb-95c6-926d89a68cb9.png)
as you can see on the top side its going offset and getting cropped as going off frame how to increase frame size @ top as it float @ bottom

**Comment by mpurses** [comment]
Gotcha, thanks for your help. 

And for moving the rocket launches higher, there really isnt a good way around it right now with how Rainmeter works, you will have to shift every Meter down to compensate for it, and with how many meters/calculations there are it will be a mess getting it to go higher. 
I'll try to think through a new layout/option for the next version in the mean time.

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/120255042-b7dde900-c2a8-11eb-949b-c2e42b3648b2.png)
 
found new issue today, i think we need text wrapping its gng off body

**Comment by mpurses** [comment]
Ya that's an issue I wasn't sure if I wanted to fix yet, I can't wrap as that throws off my formatting. So I have to just cut of excess. I might fix (cut) in the next version.

**Comment by shaktishekhar** [comment]
> Ya that's an issue I wasn't sure if I wanted to fix yet, I can't wrap as that throws off my formatting. So I have to just cut of excess. I might fix (cut) in the next version.

ok am trying to find my self how to trim json response or how to use trim function of native rainmeter anyways thnx :-)

**Comment by mpurses** [comment]
You can add a regex substitute like:
"^(.{32}).+$":"\1..."
this trims the string if over 32 characters...
![Screenshot 2021-06-01 134017](https://user-images.githubusercontent.com/642218/120374513-41101280-c2df-11eb-8141-c7eae1b20bcc.png)

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/120376056-0d61d680-c339-11eb-8cda-93e284c0809d.png)

world like charm thank you soo much buddy :-)

**Comment by mpurses** [comment]
@shaktishekhar Could you test out this Pre-release, it should have everything fixed. (Found another bug where the times didn't update properly) And I want to make sure the upgrade goes well, it should preserve all your existing Variables (custom changes).

https://github.com/mpurses/Sonder/releases/tag/v21.6.0

**Comment by shaktishekhar** [comment]
![image](https://user-images.githubusercontent.com/4972171/120847588-51e7af00-c591-11eb-8c8f-05c61a865c89.png)

it is going little bit out of  frame 

when i did its showing correct

![image](https://user-images.githubusercontent.com/4972171/120847639-6461e880-c591-11eb-8b65-0fcf1be4789d.png)

i tested in vmware so that i can compare 1 to 1 i upgraded my current settings are intact everything seems fine when i upgrade except that rocket make background little wider or trim more char i think

Before update
![image](https://user-images.githubusercontent.com/4972171/120847791-97a47780-c591-11eb-9235-1d237942a318.png)

After update
![image](https://user-images.githubusercontent.com/4972171/120847821-a0954900-c591-11eb-9064-1144f1f1fd15.png)

**Comment by mpurses** [comment]
Thanks for testing, The font I'm using isn't monospaced so 32 characters with a different location (string of characters) will have different lengths, so I'm just going to stick with 32 for now until I see more locations come through. I may adjust in a future update.
