### ISSUE TITLE
Custom wallpaper not loading with applying theme

### ISSUE THREAD

**Issue by txwhistler** [mpurses/Sonder#18]
Version: v21.6.0

When applying custom themes via the Themes Settings, the custom wallpaper of the theme is intermittently not loading.  I haven't been able to identify a pattern yet.

**Comment by txwhistler** [comment]
This seems to be consistently happening with only certain wallpapers. Maybe there is a problem with the image itself.

**Comment by mpurses** [comment]
Could you attach the wallpapers it is happening with (or if you see it only happening with a certain filetype).

If the wallpaper fails to apply, I don't think Rainmeter will give any feedback to help me, but check the Rainmeter log just in case.

One thing you could try to do is attempt to save the theme again (just save over with the save name). This will re-save the image. It could have just not saved a good image the first time.

There are other things you can do to get around this issue: In "Sonder\@Resources\Presets\Preset", the inc files there point to the wallpaper files in the Wallpapers folder. You can try to just save the original file there or just point to it in the inc file. But I would prefer to find out/fix the underlining issue.
