### ISSUE TITLE
WeatherExtd/2/3.ini Issue.

### ISSUE THREAD

**Issue by prgbmk** [mpurses/Sonder#2]
I found some Issue.
If modify Main Setting -> Weather -> Scale's Value set below 1.0 Skin.
Mouse Over Action's Hour Weather Icons offset is not correctly.(Icons are arranged to the upper right direction)

I attach fixed ini Files. Check this out.

[Weather.zip](https://github.com/mpurses/Sonder/files/5250113/Weather.zip)

**Comment by mpurses** [comment]
Thank you for finding that and taking the time to fix it. Fixed it on my side and will be included in the next update.

**Comment by mpurses** [comment]
Fixed in 2.6.0
