### ISSUE TITLE
'Settings' reopening on rainmeter refresh despite unloading

### ISSUE THREAD

**Issue by mountain-se** [mpurses/Sonder#27]
Hi, I apologize if this is an issue with Rainmeter or working as intended. I'm new to the program, but this seems like a bug to me.

On Rainmeter startup, 'Refresh All,' and other actions which refresh skins, the Sonder settings skin will pop up onto the display. This happens regardless of unloading it or attempting to change it to a different settings skin (Calendar settings, etc). If this _is_ working as intended, I do see the reasoning, but it's rather annoying!

Thanks. Love the skin.

**Comment by mpurses** [comment]
The only reason the settings page will load automatically is if you are not on the latest version and it is notifying you to update to the latest release, like this:
![update](https://user-images.githubusercontent.com/642218/130307143-7f186b42-1202-4043-8f6f-666de52f1e4e.png)

If this is not the case, let me know.

**Comment by mountain-se** [comment]
Ah ok, that solves it. Thanks you!
