### ISSUE TITLE
Additional GPU Clock and Fan shown

### ISSUE THREAD

**Issue by Hype-hash** [mpurses/Sonder#29]
Hi there,

I've got a small issue. Whenever I uncheck and check "GPU Clock/Temp" and "Fan Information" it's adding additional two lines as if there would be a second GPU, but I only have one.

https://i.imgur.com/Mc79HWY.jpeg

Cheers
Hype

**Comment by mpurses** [comment]
Should be fixed in latest 21.11.1 update

Thanks for letting me know.
