### ISSUE TITLE
different locations showing same time on World Map

### ISSUE THREAD

**Issue by L0bit0** [mpurses/Sonder#30]
Hi

first of all thanks for this great skin.

I am using world map to show different locations and times, but all cities show same time (see screenshot). i am missing any configuration or is an issue?

![Image 063](https://user-images.githubusercontent.com/10359623/141473590-f8c198e1-6f4f-4680-a90e-a146048e25e8.jpg)
Thanks

**Comment by mpurses** [comment]
I can confirm this is happening for me too, I'm not sure why yet, as a manual API call to TimeZoneDB is still working in the browser. I'll figure it out.

**Comment by mpurses** [comment]
[TimeZoneDBApi.zip](https://github.com/mpurses/Sonder/files/7528322/TimeZoneDBApi.zip)

Copy the files in this zip to "...Documents\Rainmeter\Skins\Sonder\@Resources\TimeZones"

They changed their API slightly.

After refreshing the skin, go to the map settings and hit the update time zones button. Let me know if that fixes it for you.

**Comment by mpurses** [comment]
Fixed in 21.11.1 update

**Comment by L0bit0** [comment]
Hi

thasnk for the quick response!

I tried with the files and it worked, bu i had to remove and add cities again (in case anyone is tring)

Thanks again
