### ISSUE TITLE
Sonder Space utilizing significant CPU resource

### ISSUE THREAD

**Issue by shaktoo1** [mpurses/Sonder#33]
Hi mpurses ,
I have to congratulate first on such an amazing skin suite .
I really love the space skin with world map & time zones  but I am not utilizing it as it has a significant drain on my CPU resoucres  its constantly @ 35%.
Is that the case for you or others as well or is there an issue in my setup ?
Is there anything  that could be done ?

**Comment by mpurses** [comment]
Make sure you have Hardware Acceleration enabled in the Rainmeter settings. The way Rainmeter renders images requires the GPU.  So any image heavy skin will need this enabled.  There is not that much continuous CPU calculations being done in the skin, it's just Rainmeter's image rendering engine.  Let me know what that decreases the CPU to.

![Untitled](https://user-images.githubusercontent.com/642218/143690843-800c2059-64a8-4614-b2c1-924ea5c4a612.png)
e

**Comment by shaktoo1** [comment]
Amazing & thanks for the tip that resolved it perfectly !
