### ISSUE TITLE
Error when using settings panel

### ISSUE THREAD

**Issue by drdogbot7** [mpurses/Sonder#4]
I can't update any settings using the settings panel. The changes don't take, and I get this message in the logs:

`!WriteKeyValue: Failed to write to: C:\Users\jerem\Documents\Rainmeter\Skins\Sonder\@Resources\Variables.inc (Sonder\Settings\! Settings-All.ini)`

I'm able to update the file manually without issue.

**Comment by drdogbot7** [comment]
Resolved. This was an issue with windows' "ransomeware protection'. It was blocking rainmeter.exe from changing the skin files.

**Comment by mpurses** [comment]
Interesting. Thanks for letting me know what fixed it incase it happens for other users.
