### ISSUE TITLE
Somder/Space eats loads of CPU

### ISSUE THREAD

**Issue by Unc3nZureD** [mpurses/Sonder#42]
On my setup with a CPU of: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz

If I have the 'Space' widget loaded, Rainmeter eats ~10-15% of the CPU.
If I disable the widget, the CPU usage falls back to 1-4%

Is it something that's possible to reproduce on other systems as well or maybe it's just my setup? Is it doing something that heavy which may give ~10% extra CPU usage? :O

Thank you :)

Ps.: I love the theme even without the Space widget and thank you for sharing it :)

**Comment by mpurses** [comment]
Make sure hardware acceleration is enabled.

See here: https://github.com/mpurses/Sonder/issues/33#issuecomment-980735433

**Comment by Unc3nZureD** [comment]
Ah, allright, PEBKAC 😄
