### ISSUE TITLE
Weather skin not pupulated (blank, shows no data)

### ISSUE THREAD

**Issue by Awac1991** [mpurses/Sonder#43]
First of all, thank you for creating such a stylish and cool skin, I just love it.

Weather skin (using extd2 version) stopped showing any data the other day. I've tried changing to another location, disabling auto-detect location and putting one myself... Still nothing. If I click on it with the middle mouse button (wheel) to update it, it blinks for a second but still shows no data.

Thanks again for your help
![2022-04-24_18h00_26](https://user-images.githubusercontent.com/104315749/164985308-9ecbe0de-ecb0-4b25-9934-a1602b079c39.png)
!

**Comment by mpurses** [comment]
It looks like you're not on the latest version.  Try downloading and installing the latest and see if that fixes it: https://github.com/mpurses/Sonder/releases/download/v22.1.0/Sonder_22.1.0.rmskin

**Comment by Awac1991** [comment]
You are totally right! I updated and it's working perfectly again. For some reason I didn't get the notification of a new version that I usually get... Thanks a lot!
