### ISSUE TITLE
WIFI Toogle not working after 22H2 update.

### ISSUE THREAD

**Issue by Ashutosh002** [mpurses/Sonder#51]
Sonder Version: 22.1.0

**Comment by mpurses** [comment]
Microsoft likes to change UI elements around and it can break the number of tabs it takes to toggle the Wifi.  I don't have access to _truly_ toggle wifi programmatically (requires admin rights). So I open up the Wifi settings and send tab keys until im at the On/Off button. You can change these in the settings. Sometimes it takes a bit of trial and error to find the right number.
![image](https://user-images.githubusercontent.com/642218/198431115-b2e69834-646e-40b4-b48d-0716dd8acbc3.png)

**Comment by Ashutosh002** [comment]
Thank you!
